apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sysdigagents.sysdig.com
spec:
  group: sysdig.com
  names:
    kind: SysdigAgent
    listKind: SysdigAgentList
    plural: sysdigagents
    singular: sysdigagent
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysdig-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-operator
subjects:
- kind: ServiceAccount
  name: sysdig-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdig-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sysdig-operator
  template:
    metadata:
      labels:
        name: sysdig-operator
    spec:
      serviceAccountName: sysdig-operator
      containers:
        - name: sysdig-operator
          # Replace this with the built image name
          image: docker.io/sysdiglabs/sysdig-operator:1.4.13
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sysdig-operator"
