# permissions for end users to edit sysdigagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sysdigagent-editor-role
rules:
- apiGroups:
  - sysdig.com
  resources:
  - sysdigagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sysdig.com
  resources:
  - sysdigagents/status
  verbs:
  - get
