name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      # - name: Login to Artifactory
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.internal.sysdig.com
      #     username: ${{ secrets.ARTIFACTORY_USERNAME }}
      #     password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Login to Red Hat Connect Scanning
        uses: docker/login-action@v1
        with:
          registry: scan.connect.redhat.com
          username: ${{ secrets.REDHAT_SCAN_CONNECT_USERNAME }}
          password: ${{ secrets.REDHAT_SCAN_CONNECT_PASSWORD }}
      - name: Build operator image
        id: build_image
        run: |
          set -ex

          make docker-build

          BUILT_IMAGE=$(docker images registry.connect.redhat.com/sysdig/sysdig-operator --format "{{.Repository}}:{{.Tag}}" | head -n 1)
          echo "::set-output name=built_image::${BUILT_IMAGE}"

          BUILT_IMAGE_TAG=$(docker images registry.connect.redhat.com/sysdig/sysdig-operator --format "{{.Tag}}" | head -n 1)
          echo "::set-output name=built_image_tag::${BUILT_IMAGE_TAG}"
      - name: Push images
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ steps.build_image.outputs.built_image }}
          dst: |
            scan.connect.redhat.com/ospid-2953a149-0b38-4515-9768-dd548c234edb/sysdig-operator:${{ steps.build_image.outputs.built_image_tag }}
      #       docker.internal.sysdig.com/utils/sysdig-operator:${{ steps.build_iamges.outputs.built_image_tag }}

